Repository KDG-Develop-Hub/social-mobile, pull requests merged in 2024-06, with the labels that each got.

#8 カスタムテーマクラスの実装
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  README.md
  ios/Podfile.lock
  lib/presentation/social_mobile.dart
  lib/utils/constants/app_color.dart
  lib/utils/state/overlay_loading_provider.g.dart
  lib/utils/theme/extension/theme_extension.dart
  lib/utils/theme/extension/theme_extension.tailor.dart
  lib/utils/theme/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation📄, new feature🎉

#11 グローバルなTextFieldコンポーネントを実装
  lib/presentation/components/text_field_widget.dart
  lib/utils/theme/extension/theme_extension.dart
  lib/utils/theme/extension/theme_extension.tailor.dart
  pubspec.lock
  pubspec.yaml
Labels: new feature🎉

#15 BottomNavigationBarの実装
  assets/images/apude_icon.svg
  assets/images/kimitoha_icon.svg
  assets/images/mitukeru_icon.svg
  assets/images/sette_icon.svg
  assets/images/siriai_icon.svg
  lib/presentation/components/bottom_navigation/bottom_navigation.dart
  lib/presentation/components/bottom_navigation/provider/bottom_navigation_notifier.dart
  lib/presentation/components/bottom_navigation/provider/bottom_navigation_notifier.g.dart
  lib/presentation/home/apude_screen.dart
  lib/presentation/home/kimitoha_screen.dart
  lib/presentation/home/mitukeru_screen.dart
  lib/presentation/home/sette_screen.dart
  lib/presentation/home/siriai_screen.dart
  lib/presentation/social_mobile.dart
  lib/utils/gen/assets.gen.dart
  lib/utils/routes/routes.dart
  lib/utils/theme/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#10 💡 Multi-Language Setting
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_ja.i18n.json
  lib/main.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/provider/locale_service.dart
  lib/presentation/provider/locale_service.g.dart
  lib/presentation/social_mobile.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#19 ViewModelの廃止
  README.md
  assets/icons/friends_icon.svg
  assets/icons/profile_icon.svg
  assets/icons/search_icon.svg
  assets/icons/settings_icon.svg
  assets/icons/update_icon.svg
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/i18n/strings_ja.i18n.json
  lib/presentation/components/bottom_navigation/bottom_navigation.dart
  lib/presentation/friends/friends_screen.dart
  lib/presentation/home/kimitoha_screen.dart
  lib/presentation/profile/profile_screen.dart
  lib/presentation/search/search_screen.dart
  lib/presentation/settings/settings_screen.dart
  lib/presentation/update/provider/update_notifier.dart
  lib/presentation/update/provider/update_notifier.g.dart
  lib/presentation/update/update_screen.dart
  lib/utils/gen/assets.gen.dart
  lib/utils/routes/routes.dart
  pubspec.yaml
Labels: 📄 documentation, 🎉 new feature

#21 GoRouterBuilderの適用
  lib/presentation/components/bottom_navigation.dart
  lib/presentation/components/bottom_navigation/provider/bottom_navigation_notifier.dart
  lib/presentation/components/bottom_navigation/provider/bottom_navigation_notifier.g.dart
  lib/presentation/social_mobile.dart
  lib/utils/routes/app_router.dart
  lib/utils/routes/app_router.g.dart
  lib/utils/routes/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature

#22 テーマのリニューアル
  lib/presentation/components/bottom_navigation.dart
  lib/presentation/components/text_field_widget.dart
  lib/presentation/social_mobile.dart
  lib/utils/theme/extension/theme_extension.dart
  lib/utils/theme/extension/theme_extension.tailor.dart
  lib/utils/theme/theme.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎉 new feature, ♻️ refactoring
